---
- name: Creates nginx conf backup dir
  file: path=/etc/nginx.old state=directory
  register: nginx_adv_backup_dir
  when: nginx_adv_backup_dir is not defined

- name: Backup standard nginx folder
  command: cp -r /etc/nginx/ /etc/nginx.old
  register: nginx_backuped
  when: (nginx_adv_backup_dir) and (nginx_adv_seted is not defined)

- name: Clear /etc/nginx
  shell: rm -rf /etc/nginx/*
  register: nginx_backuped
  when: nginx_backuped

- name: Clone nginx advanced drupal config
  git: >
    repo=https://github.com/perusio/drupal-with-nginx
    dest=/etc/nginx
  notify: restart nginx
  register: nginx_adv_seted
  when: (nginx_backuped|succdess) and (nginx_adv_seted is not defined)