---

- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - vars/git.yml
    - vars/dotfiles.yml
    - vars/mysql.yml
    - vars/php.yml
    - vars/phpstorm.yml
    - vars/main.yml

  pre_tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/prepare.yml

  roles:
    - geerlingguy.git
    - geerlingguy.dotfiles
    - tersmitten.nano
    - { role: geerlingguy.nginx, when: not drupal_nginx_conf_installed.stat.exists }
    - adminer
    - geerlingguy.php
    - geerlingguy.mysql
    - geerlingguy.composer
    - drush
    - qc
    - drush_rr
    - java
    - kosssi.phpstorm
    - vcabourdin.chrome
    - terminal
    - git_power
    - grafics
    - slack
    - xchat
    - skype
    - valentine94.sudoers
    - mrlesmithjr.nodejs
    - tersmitten.virtualbox

  tasks:
    - include: tasks/drupal_nginx_conf.yml
    #- include: tasks/php_fpm_setup.yml

  vars_prompt:
    - name: "git_user_name"
      prompt: "Git user name"
      private: no

    - name: "git_user_email"
      prompt: "Git user email"
      private: no

  post_tasks:
    - include: tasks/phpcs_complete.yml
    - include: tasks/complete.yml
