---
- src: geerlingguy.git
- src: geerlingguy.dotfiles
- src: geerlingguy.nginx
- src: geerlingguy.php
  version: 1.7.0
- src: geerlingguy.mysql
- src: geerlingguy.composer
#- src: geerlingguy.drush
- src: tersmitten.nano
#- src: kosssi.phpstorm
#- src: mrlesmithjr.nodejs
#- src: valentine94.sudoers
#- src: vcabourdin.chrome
