---
# Nano.
- src: tersmitten.nano
# PHPStorm.
- src: tersmitten.phpstorm
  version: v1.0.1
# NodeJS.
- src: tersmitten.nodejs
  version: v2.1.0
# Sudoers fix.
- src: valentine94.sudoers
# Google Chrome.
- src: vcabourdin.chrome
# Dotfiles.
- src: geerlingguy.dotfiles
# Git.
- src: geerlingguy.git
  version: 1.1.1
# NginX.
- src: geerlingguy.nginx
  version: 1.9.2
# PHP.
- src: geerlingguy.php
  version: 1.7.0
# MySQL.
- src: geerlingguy.mysql
  version: 2.2.1
# Composer.
- src: geerlingguy.composer
  version: 1.4.0
# VirtualBox.
- src: tersmitten.virtualbox
  version: v1.0.3
# Vagrant.
- src: tersmitten.vagrant
  version: v1.0.2
# Mailcatcher.
- src: Oefenweb.mailcatcher
  version: v1.0.0
