---
- src: geerlingguy.git
- src: geerlingguy.dotfiles
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: geerlingguy.mysql
- src: geerlingguy.composer
- src: geerlingguy.drush
- src: tersmitten.nano
- src: kosssi.phpstorm