---

- name: Check if /etc/php5/fpm.old is already exists.
  stat: path=/etc/php5/fpm.old
  register: php_fpm_old

- name: Creates php-fpm conf backup dir.
  file:
    path: /etc/php5/fpm.old
    state: directory

- name: Backup standard php-fpm folder.
  shell: "cp -r /etc/php5/fpm/* /etc/php5/fpm.old"
  register: php_fpm_backuped
  when: php_fpm_old.stat.exists == false

- name: Remove /etc/php5/fpm.
  shell: rm -rf /etc/php5/fpm
  when: php_fpm_old.stat.exists == false

- name: Clone php5-fpm config.
  git:
    repo: https://github.com/perusio/php-fpm-example-config
    dest: "{{ downloads }}/php-fpm-example-config"
    version: unix
    update: true

- name: Symlink php-fpm-example-config to /etc/php5/fpm.
  file:
    src: "{{ downloads }}/php-fpm-example-config/fpm"
    path: /etc/php5/fpm
    state: link
  notify: restart webserver
  when: php_fpm_old.stat.exists == false
