---

# xChat.
- name: Ensure xChat is installed.
  apt: pkg=xchat state=latest

# HipChat.
- name: HipChat | Add repository into sources list.
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present

- name: HipChat | Add apt key.
  apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present

- name: Check if HipChat is already installed.
  stat: path=/usr/bin/hipchat
  register: hipchat_installed

- name: Update apt cache if HipChat is not yet installed.
  apt: update_cache=yes
  when: hipchat_installed.stat.exists == false

- name: HipChat | Installing.
  apt: name=hipchat state=installed

- name: Add HipChat to autostart.
  file:
    src: /usr/share/applications/hipchat.desktop
    path: /etc/xdg/autostart/hipchat.desktop
    state: link

- name: HipChat | Install missing library
  apt: name=libxcb-keysyms1-dev

# Slack.
- name: Slack | Check if Slack is installed
  command: dpkg-query -W slack
  register: slack_deb
  failed_when: slack_deb.rc > 1
  changed_when: slack_deb.rc == 1

- name: Slack | Downolad package
  get_url:
    url: {{slack_deb_url}}
    dest: /temp/slack.deb
  when: slack_deb.rc == 1

- name: Slack | Install Slack
  apt:
    deb: /temp/slack.deb
  sudo: true
  when: slack_deb.rc == 1
