---

# xChat.
- name: Ensure xChat is installed.
  apt: pkg=xchat state=latest

# Slack.
- name: Slack | Check if Slack is installed
  command: dpkg-query -W slack
  register: slack_deb
  failed_when: slack_deb.rc > 1
  changed_when: slack_deb.rc == 1

- name: Slack | Downolad package
  get_url:
    url: "{{slack_deb_url}}"
    dest: "/home/{{ ansible_env.USER }}/Downloads/slack.deb"
  sudo: true
  when: slack_deb.rc == 1

- name: Slack | Install Slack
  apt:
    deb: "/home/{{ ansible_env.USER }}/Downloads/slack.deb"
  sudo: true
  when: slack_deb.rc == 1
