---

- name: Check if Slack is installed
  command: dpkg-query -W slack
  register: slack_deb
  failed_when: slack_deb.rc > 1
  changed_when: slack_deb.rc == 1

- name: Install Slack
  apt: deb="{{slack_local_source}}"
  sudo: true
  when: slack_deb.rc == 1
