- name: Add architecture for x64 systems
  sudo: yes
  shell: "dpkg --add-architecture i386"
  when: ansible_userspace_bits == "64"

- name: Install Skype
  script: {{ ansible_env.PWD }}/roles/skype/files/install_skype.sh creates=/usr/share/skype
  sudo: yes

- name: Add Skype to autostart.
  file:
    src: /usr/share/applications/skype.desktop
    path: /etc/xdg/autostart/skype.desktop
    state: link
