- name: Create Adminer folder
  file:
    path: /usr/share/adminer
    state: directory

- name: Adminer downloading
  shell: "wget http://www.adminer.org/latest.php -O /usr/share/adminer/latest.php"
  sudo: yes

- name: Adminer symlink
  shell: "ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php"
  sudo: yes

- name: Adminer vhost
  copy: src={{ ansible_env.PWD }}/roles/adminer/files/adminer dest=/etc/nginx/sites-available/adminer mode=0644

- name: Create adminer vhost symlink
  file: src=/etc/nginx/sites-available/adminer dest=/etc/nginx/sites-enabled/adminer state=link

- name: Add adminer to hosts
  shell: "echo '127.0.0.1 adminer' >> /etc/hosts"
  sudo: yes

- name: Restart nginx server
  shell: "service nginx restart"
  sudo: yes
